[package]
name = "navigator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# cli
clap = { version = "4.0", features = ["derive", "env", "wrap_help"] }
anyhow = "1.0"
